spring:
  application:
    name: decision-service
server:
  port: 8087


decision:
  service:
    credit:
      score:
        min-score: 600
        url:
          equifax: http://localhost:9093/api/v1/demo
          experian: http://localhost:9092/api/v1/demo
          transunion: http://localhost:9091/api/v1/demo
management:
  security:
    enabled: false


  endpoints:
    web:
      exposure:
        include: "*"
    health:
      show-details: always
  info:
    env:
      enabled: true
