spring:
  application:
    name: decision-service
server:
  port: 8087


decision:
  service:
    credit:
      score:
        min-score: 500
        url:
          equifax: http://localhost:9093/api/v1/demo
          experian: http://localhost:9092/api/v1/demo
          transunion: http://localhost:9091/api/v1/demo
